config/routes.rb
ANR::Application.routes.draw do
  resources :furnitures


  root :to => 'home#index'
end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
  attr_accessible :available, :description, :image, :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  # GET /furnitures
  # GET /furnitures.json
  def index
    @furnitures = Furniture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @furnitures }
    end
  end

  # GET /furnitures/1
  # GET /furnitures/1.json
  def show
    @furniture = Furniture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @furniture }
    end
  end

  # GET /furnitures/new
  # GET /furnitures/new.json
  def new
    @furniture = Furniture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @furniture }
    end
  end

  # GET /furnitures/1/edit
  def edit
    @furniture = Furniture.find(params[:id])
  end

  # POST /furnitures
  # POST /furnitures.json
  def create
    @furniture = Furniture.new(params[:furniture])

    respond_to do |format|
      if @furniture.save
        format.html { redirect_to @furniture, notice: 'Furniture was successfully created.' }
        format.json { render json: @furniture, status: :created, location: @furniture }
      else
        format.html { render action: "new" }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /furnitures/1
  # PUT /furnitures/1.json
  def update
    @furniture = Furniture.find(params[:id])

    respond_to do |format|
      if @furniture.update_attributes(params[:furniture])
        format.html { redirect_to @furniture, notice: 'Furniture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1
  # DELETE /furnitures/1.json
  def destroy
    @furniture = Furniture.find(params[:id])
    @furniture.destroy

    respond_to do |format|
      format.html { redirect_to furnitures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/furnitures/_form.html.erb
<%= form_for(@furniture) do |f| %>
  <% if @furniture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>

      <ul>
      <% @furniture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/furnitures/edit.html.erb
<h1>Editing furniture</h1>

<%= render 'form' %>

<%= link_to 'Show', @furniture %> |
<%= link_to 'Back', furnitures_path %>

app/views/furnitures/index.html.erb
<h1>Listing furnitures</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @furnitures.each do |furniture| %>
  <tr>
    <td><%= furniture.image %></td>
    <td><%= furniture.name %></td>
    <td><%= furniture.description %></td>
    <td><%= furniture.price %></td>
    <td><%= furniture.available %></td>
    <td><%= link_to 'Show', furniture %></td>
    <td><%= link_to 'Edit', edit_furniture_path(furniture) %></td>
    <td><%= link_to 'Destroy', furniture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Furniture', new_furniture_path %>

app/views/furnitures/new.html.erb
<h1>New furniture</h1>

<%= render 'form' %>

<%= link_to 'Back', furnitures_path %>

app/views/furnitures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @furniture.image %>
</p>

<p>
  <b>Name:</b>
  <%= @furniture.name %>
</p>

<p>
  <b>Description:</b>
  <%= @furniture.description %>
</p>

<p>
  <b>Price:</b>
  <%= @furniture.price %>
</p>

<p>
  <b>Available:</b>
  <%= @furniture.available %>
</p>


<%= link_to 'Edit', edit_furniture_path(@furniture) %> |
<%= link_to 'Back', furnitures_path %>

app/views/home/index.html.erb
<!-- begin #page - the container for everything but header -->
<div id="page">
	<div class="hero-unit">
		<div class="container">
			<h2>World Wide Web Typography</h2>
		</div>
		<!--close container--> 
	</div>
	<!--close hero-unit-->
	
	<div class="container clearfix" id="main-content"><!--begin main content-->
		<div class="row-fluid portfolio-detail"><!--begin row-fluid-->
			
			<div class="span7 offset1 image-slider" role="image-slider"> 
				
				<!-- Begin Carousel -->
				<div id="carousel" class="flexslider">
					<ul class="slides">
						<!--notice that these are background images because youtube and vimeo images fetched dynamically are not the same size-->
						<li style="background-image: url(../assets/custom-wood-work-green-recycle1);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle10);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle1);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle10);"><img src="assets/images/trans.gif"alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle1);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle10);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle1);"><img src="assets/images/trans.gif" alt=""></li>
						<li style="background-image: url(../assets/custom-wood-work-green-recycle10);"><img src="assets/images/trans.gif"alt=""></li>	
					</ul>
				</div>
				<!-- End Carousel --> 
				
				<!-- Begin Slider -->
				<div id="slider" class="flexslider">
					<ul class="slides">
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						<li> <a class="zoom-image fancyme" data-fancybox-group="portfolio" href="../demo/portfolio/1-lrg.jpg">View Larger Image</a> <img src="../assets/custom-wood-work-green-recycle17" alt=""></li>
						
					</ul>
				</div>
				<!-- End Slider --> 
				
			</div>
			<!-- close span7 primary-column-->
			
			<section class="span4 project-description" role="project-description">
				<p>Vestibulum a pulvinar massa. Donec bibendum lectus eget enim pellentesque elementum. Aenean leo diam, adipiscing vel semper aliquam, adipiscing in nisl. Vestibulum eget orci et diam lobortis tincidunt. Cras auctor nunc quis erat venenatis venenatis auctor nulla fringilla. Proin facilisis ante quis erat sodales fringilla.</p>

<div id="txt">
	<p>Coming from England and living in California is something special.I love everything about the beach, Just going down there to enjoy the waves crashing against the shoreline,Or reconnect with mother nature, maybe going out on a boat or just simply to swim and enjoy.</p> 
	<p>The beach has a huge spiritual meaning and feeling inside, my energy once leaving the beach is so uplifted,So for me to get involved with driftwood was a no brainer.
	<p>Finding a piece of driftwood and Giving it a new life instead of it rotting and decaying by turning it into a beautiful piece of art,thats the satisfaction I get to watch the piece of wood transform into it's new life is something special.</p> 
</div>
</div>

app/views/layouts/_footer.erb
	<footer id="footer" class="clearfix" style="margin-top: 600px;">

		<div class="container">

			<div class="three-fourth">

				<nav id="footer-nav" class="clearfix">

					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="elements.html">Features</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li><a href="portfolio-4-columns.html">Portfolio</a></li>
						<li><a href="contact-us.html">Contact</a></li>
					</ul>

				</nav><!-- end #footer-nav -->

				<ul class="contact-info">
					<li class="address">454 1/2 N.Stanley Ave. Los Angeles, CA 90036</li>
					<li class="phone">(323) 333-9248</li>
					<li class="email"><a href="mailto:contact@companyname.com">117driftsmith@gmail.com</a></li>
				</ul><!-- end .contact-info -->

			</div><!-- end .three-fourth -->

			<div class="one-fourth last" style="float: right; margin-right: 25px; margin-top: 5px;">

				<span class="title">Stay connected</span>

				<ul class="social-links">
					<li class="twitter"><a href="#">Twitter</a></li>
					<li class="facebook"><a href="https://www.facebook.com/anthony.e.smith.90?fref=ts">Facebook</a></li>
				</ul><!-- end .social-links -->

			</div><!-- end .one-fourth.last -->

		</div><!-- end .container -->

	</footer><!-- end #footer -->

	<footer id="footer-bottom" class="clearfix">

		<div class="container">

			<ul>
				<li>Artofnaturesresources &copy; 2012</li>
				<li><a href="https://www.odesk.com/users/~015fbce4255af90f53">Mikeeyy_3 Designs</a></li>
			</ul>

		</div><!-- end .container -->

	</footer>

app/views/layouts/_header.erb
<div id="header">
	<%= image_tag("logo.png", :alt => "" , :style =>"height: 240px; margin-top: -110px; margin-right: 5px;")%>
	
</div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ANR</title>
  <%= stylesheet_link_tag    "application", "style.css" , "jquery.flexslider-min.js" , :media => "all" %>
  <%= javascript_include_tag "application"  , "http://cloud.github.com/downloads/malsup/cycle/jquery.cycle.all.latest.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="main" class="wrapper" class="borders">
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>